
#tagsConstants.py
#@Class GPConstants
#@Author: mei yang
#@Creation: Feb-26-2014

class TAGS():
    INS_FETCH = 0x12
    INS_TR = 0x14

    TAG_CMD_DETAIL = 1
    TAG_DEVICE_ID  = 2
    TAG_RESULT = 3
    TAG_DURATION = 4
    TAG_ALPHA_ID = 5
    TAG_ADDRESS = 6
    TAG_CAP_CONFIG = 7
    TAG_SUBADDRESS = 8
    TAG_SSSTRING = 9
    TAG_USSDSTRING = 0x0A
    TAG_SMS_TPDU = 0x0B
    TAG_CELL_BROADCAST = 0x0C
    TAG_TEXT_STRING = 0x0D
    TAG_TONE = 0x0E
    TAG_ITEM = 0x0F
    TAG_ITEM_ID = 0x10
    TAG_RESPONSE_LENGTH = 0x11


    TAG_BEARER_DESCRIPTION = 0x35
    TAG_CHANNEL_DATA = 0x36
    TAG_CHANNEL_DATA_LENGTH = 0x37
    TAG_CHANNEL_STATUS = 0x38
    TAG_BUFFER_SIZE = 0x39
    TAG_UICC_TERMINAL_ITL = 0x3C
    TAG_OTHER_ADDRESS = 0x3E
    TAG_ACCESS_TECHNOLOGY = 0x3F
    TAG_DISPLAY_PARAMETER = 0x40

    PCMD_REFRESH = 1
    PCMD_MORETIME = 2
    PCMD_POLL_INTERVAL = 3
    PCMD_POLL_OFF = 4
    PCMD_SETUP_EVENTLIST = 5
    PCMD_SETUP_CALL = 0x10
    PCMD_SEND_SS = 0x11
    PCMD_SEND_USSD = 0x12
    PCMD_SEND_SMS = 0x13
    PCMD_SEND_DTMF = 0x14
    PCMD_LAUNCH_BROWSER = 0x15
    PCMD_PLAY_TONE = 0x20
    PCMD_DISPLAY_TEXT = 0x21
    PCMD_GET_INKEY = 0x22
    PCMD_GET_INPUT = 0x23
    PCMD_SELECT_ITEM = 0x24
    PCMD_SET_UP_MENU = 0x25
    PCMD_PROVIDE_LOCAL_INFO = 0x26
    PCMD_TIMER_MANAGEMENT = 0x27
    PCMD_SET_UP_IDLE_TEXT = 0x28
    PCMD_PERFORM_CARD = 0x30
    PCMD_POWER_ON = 0x31
    PCMD_POWER_OFF = 0x32
    PCMD_GET_READER_STATUS = 0x33
    PCMD_RUN_AT_COMMAND = 0x34
    PCMD_LANGUAGE_NOTIFICATION = 0x35
    PCMD_OPEN_CHANNEL = 0x40
    PCMD_CLOSE_CHANNEL = 0x41
    PCMD_RECEIVE_DATA = 0x42
    PCMD_SEND_DATA = 0x43
    PCMD_GET_CHANNEL_STATUS = 0x44
    PCMD_SERVICE_SEARCH = 0x45
    PCMD_GET_SERVICE_INFO = 0x46
    PCMD_DECLARE_SERVICE = 0x47
    PCMD_END_OF_PROACTIVE_SESSION = 0x81


