#gpconstants.py
#@Class GPConstants
#@Author: mei yang
#@Creation: Feb-26-2014


INS_DELETE = 0xE4
INS_GETDATA = 0xCA
INS_GETSTATUS = 0xF2
INS_INSTALL = 0xE6
INS_LOAD = 0xE8
INS_MANAGECHANNEL = 0x70
INS_PUTKEY = 0xD8
INS_SELECT = 0xA4
INS_SETSTATUS = 0xF0
INS_STOREDATA = 0xE2

